
export const MetroCodesData = [
  { code: 'CMH', city: 'Columbus', state: 'Ohio', region: 'North America - East', lat: 39.9612, lon: -82.9988 },
  { code: 'IAD', city: 'Gainesville', state: 'Virginia', region: 'North America - East', lat: 38.7932, lon: -77.6142 },
  { code: 'LNK/CBF', city: 'Council Bluffs', state: 'Iowa', region: 'North America - Central', lat: 41.2619, lon: -95.8608 },
  { code: 'DFW', city: 'Midlothian', state: 'Texas', region: 'North America - Central', lat: 32.4839, lon: -96.9928 },
  { code: 'DLS', city: 'The Dalles', state: 'Oregon', region: 'North America - West', lat: 45.5946, lon: -121.1787 },
  { code: 'TUL', city: 'Pryor', state: 'Oklahoma', region: 'North America - Central', lat: 36.307, lon: -95.3155 },
  { code: 'CKV', city: 'Clarksville', state: 'Tennessee', region: 'North America - East', lat: 36.5298, lon: -87.3595 },
  { code: 'RIC', city: 'Richmond', state: 'Virginia', region: 'North America - East', lat: 37.5407, lon: -77.436 },
  { code: 'CHS', city: 'Charleston', state: 'South Carolina', region: 'North America - East', lat: 32.7765, lon: -79.9311 },
  { code: 'RNO', city: 'McCarren', state: 'Nevada', region: 'North America - West', lat: 39.5296, lon: -119.8138 },
  { code: 'SLC', city: 'Salt Lake City', state: 'Utah', region: 'North America - West', lat: 40.7608, lon: -111.891 },
  { code: 'MCI', city: 'Kansas City', state: 'Missouri', region: 'North America - Central', lat: 39.0997, lon: -94.5786 },
  { code: 'PHX', city: 'Mesa', state: 'Arizona', region: 'North America - West', lat: 33.4152, lon: -111.8315 },
  { code: 'YUL', city: 'Montreal', state: 'Quebec', region: 'North America - East', lat: 45.5017, lon: -73.5673 },
  { code: 'FWA', city: 'Fort Wayne', state: 'Indiana', region: 'North America - East', lat: 41.0793, lon: -85.1394 },
  { code: 'CLT', city: 'Charlotte', state: 'North Carolina', region: 'North America - East', lat: 35.2271, lon: -80.8431 },
  { code: 'AUS', city: 'Austin', state: 'Texas', region: 'North America - Central', lat: 30.2672, lon: -97.7431 },
  { code: 'HSV', city: 'Widows Creek', state: 'Alabama', region: 'North America - East', lat: 34.7304, lon: -86.5861 },
  { code: 'BMI', city: 'Bloomington', state: 'Illinois', region: 'North America - East', lat: 40.4842, lon: -88.9937 },
  { code: 'CID', city: 'Cedar Rapids', state: 'Iowa', region: 'North America - Central', lat: 41.9779, lon: -91.6656 },
  { code: 'FDY', city: 'Lima', state: 'Ohio', region: 'North America - East', lat: 40.7431, lon: -84.1055 },
  { code: 'SWO', city: 'Stillwater', state: 'Oklahoma', region: 'North America - Central', lat: 36.1156, lon: -97.0584 },
  { code: 'AMW', city: 'Ames', state: 'Iowa', region: 'North America - Central', lat: 42.0347, lon: -93.62 },
  { code: 'LAS', city: 'Las Vegas', state: 'Nevada', region: 'North America - West', lat: 36.1699, lon: -115.1398 },
  { code: 'LAX', city: 'Los Angeles', state: 'California', region: 'North America - West', lat: 34.0522, lon: -118.2437 },
  { code: 'ATL', city: 'Atlanta', state: 'Georgia', region: 'North America - Central', lat: 33.749, lon: -84.388 },
  { code: 'MSP', city: 'Minneapolis', state: 'Minnesota', region: 'North America - Central', lat: 44.9778, lon: -93.265 },
  { code: 'MRN', city: 'Morganton', state: 'North Carolina', region: 'North America - East', lat: 35.746, lon: -81.6882 },
  { code: 'MEM', city: 'Memphis', state: 'Tennessee', region: 'North America - East', lat: 35.1495, lon: -90.049 },
  { code: 'PHN', city: 'Clair County', state: 'Michigan', region: 'North America - East', lat: 42.9725, lon: -82.7849 },
  { code: 'ROA', city: 'Roanoke', state: 'Virginia', region: 'North America - East', lat: 37.271, lon: -79.9414 },
  { code: 'DYS', city: 'Abilene', state: 'Texas', region: 'North America - Central', lat: 32.4487, lon: -99.7331 },
  { code: 'HOU', city: 'Houston', state: 'Texas', region: 'North America - Central', lat: 29.7604, lon: -95.3698 }
];
