steps:
  # Step 0: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/constructionrfp-sandbox-943476/firebaseapphosting-images/studio:${_IMAGE_TAG}'
      - '.'

  # Step 1: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/constructionrfp-sandbox-943476/firebaseapphosting-images/studio:${_IMAGE_TAG}'

  # Step 2: Deploy to Cloud Run using the Firebase App Hosting service account
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: Deploy
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'studio'
      - '--image'
      - 'us-central1-docker.pkg.dev/constructionrfp-sandbox-943476/firebaseapphosting-images/studio:${_IMAGE_TAG}'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--quiet'
      - '--service-account'
      - '<REDACTED_PII>'
      # Add other runConfig settings from apphosting.yaml if needed, e.g.:
      # - '--min-instances=0'
      # - '--max-instances=100'
      # - '--concurrency=80'
      # - '--cpu=1'
      # - '--memory=512Mi'

# Artifacts to be produced by the build
images:
  - 'us-central1-docker.pkg.dev/constructionrfp-sandbox-943476/firebaseapphosting-images/studio:${_IMAGE_TAG}'

# Options for the build
options:
  logging: CLOUD_LOGGING_ONLY

# User-defined substitutions
substitutions:
  _IMAGE_TAG: $(echo ${SHORT_SHA:-latest})
