
// This file is not intended to be modified.
//
// This file is automatically generated by the Firebase Studio.
// You can find more information about this at: https://firebase.google.com/docs/studio
'use client';

import {useState, useEffect} from 'react';
import {
  onSnapshot,
  Query,
  DocumentData,
  FirestoreError,
  QuerySnapshot,
} from 'firebase/firestore';

export function useCollection<T>(
  query: Query<DocumentData> | null
): {
  data: (T & {id: string})[] | null;
  loading: boolean;
  error: FirestoreError | null;
} {
  const [data, setData] = useState<(T & {id: string})[] | null>(null);
  const [loading, setLoading] = useState<boolean>(true);
  const [error, setError] = useState<FirestoreError | null>(null);

  useEffect(() => {
    if (!query) {
      setLoading(false);
      return;
    }
    
    setLoading(true);

    const unsubscribe = onSnapshot(
      query,
      (snapshot: QuerySnapshot<DocumentData>) => {
        const docs = snapshot.docs.map(
          (doc) => ({id: doc.id, ...doc.data()} as T & {id: string})
        );
        setData(docs);
        setLoading(false);
      },
      (err: FirestoreError) => {
        setError(err);
        setLoading(false);
        console.error(err);
      }
    );

    return () => unsubscribe();
  }, [query]);

  return {data, loading, error};
}
