
// This file is not intended to be modified.
//
// This file is automatically generated by the Firebase Studio.
// You can find more information about this at: https://firebase.google.com/docs/studio
'use client';

import {useState, useEffect} from 'react';
import {
  onSnapshot,
  DocumentReference,
  DocumentData,
  FirestoreError,
  DocumentSnapshot,
} from 'firebase/firestore';

export function useDoc<T>(
  docRef: DocumentReference<DocumentData>
): {
  data: (T & {id: string}) | null;
  loading: boolean;
  error: FirestoreError | null;
} {
  const [data, setData] = useState<(T & {id: string}) | null>(null);
  const [loading, setLoading] = useState<boolean>(true);
  const [error, setError] = useState<FirestoreError | null>(null);

  useEffect(() => {
    setLoading(true);
    const unsubscribe = onSnapshot(
      docRef,
      (snapshot: DocumentSnapshot<DocumentData>) => {
        if (snapshot.exists()) {
          setData({id: snapshot.id, ...snapshot.data()} as T & {id: string});
        } else {
          setData(null);
        }
        setLoading(false);
      },
      (err: FirestoreError) => {
        setError(err);
        setLoading(false);
        console.error(err);
      }
    );

    return () => unsubscribe();
  }, [docRef]);

  return {data, loading, error};
}
