
// This file is not intended to be modified.
//
// This file is automatically generated by the Firebase Studio.
// You can find more information about this at: https://firebase.google.com/docs/studio
'use client';

import React, {ReactNode} from 'react';
import {FirebaseProvider} from './provider';
import {initializeFirebase} from './index';

// Initializing Firebase on the client-side
const firebaseInstance = initializeFirebase();

export function FirebaseClientProvider({children}: {children: ReactNode}) {
  return (
    <FirebaseProvider value={firebaseInstance}>{children}</FirebaseProvider>
  );
}
