
// This file is not intended to be modified.
//
// This file is automatically generated by the Firebase Studio.
// You can find more information about this at: https://firebase.google.com/docs/studio
const firebaseConfig = {
  "apiKey": "mock-api-key",
  "authDomain": "mock-auth-domain",
  "projectId": "marcus-automation-suite",
  "storageBucket": "mock-storage-bucket",
  "messagingSenderId": "mock-messaging-sender-id",
  "appId": "mock-app-id"
};

export default firebaseConfig;
